config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: 'cocktails#index'
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :new, :show, :create, :destroy] do
    resource :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail

  validates :description, presence: true
  validates_uniqueness_of :cocktail, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end
  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
  end
  def new
    @cocktail = Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner">
  <h1>drink Drink DRINK</h1>
  <div class="button">
    <%= link_to "Create Cocktail", new_cocktail_path, class: 'banner-btn' %>
  </div>
</div>
<%= image_tag ("Drink.jpg"), alt: "Drink", width: '100%', class: "banner-image" %>
<div class="cocktail-cards">
  <ul>
    <% @cocktails.each do |cocktail| %>
      <% if cocktail.photo.attached? %>
        <div class="cocktail-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 240, crop: :fill %>')">
      <% else %>
        <div class="cocktail-card">
      <% end %>
        <%= link_to "#{cocktail.name}", cocktail_path(cocktail), class: "cocktails-title" %>
        <%= link_to cocktail_path(cocktail), method: :delete,
        data: { confirm: "Are you sure?"}, class: "cocktail-delete" do %>
        <i class="fas fa-trash"></i>
        <% end %>
      </div>
    <% end %>
  </ul>
</div>

app/views/cocktails/new.html.erb
<div class="create-container">
  <h2>Create a new Cocktail</h2>
    <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: "home-button" %>
  <% end %>
  <%= link_to "back to HOME", root_path, class: "home-button" %>
</div>

app/views/cocktails/show.html.erb
<div class="create-container">
  <h2><%= @cocktail.name %></h2>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill, class: "show-image" %>
  <ul>
    <% @doses.each do |dose| %>
      <span class="dose"><%= dose.description %> <%= dose.ingredient.name %></span>
      <%= link_to dose_path(dose),
          method: :delete,
          data: { confirm: "Are you sure?"}, class: "dose-delete" do %>
          <i class="fas fa-trash"></i>
        <% end %>
    <% end %>
  </ul>
    <%= link_to "add Ingredient", new_cocktail_doses_path(@cocktail), class: "home-button" %>
    <%= link_to "back to HOME", root_path, class: "home-button" %>
</div>

app/views/doses/new.html.erb
<div class="create-container">
  <h2>Create a new Dose</h2>
  <div id="create-form">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.button :submit, class: "home-button" %>
  <% end %>
  </div>
    <%= link_to "back to HOME", root_path, class: "home-button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>